project:
  type: "website"
  title: "Development Economics (Fall 2025)"
  output-dir: _site
  render: # Add here all folders that should be rendered
    - "index.qmd"
    - "content/index.qmd"
    - "content/tutorials.qmd"
    - "content/material/*.qmd"
    - "content/material/session*/*.qmd"
    - "content/tutorials/*.qmd"
    - "content/tutorials/*/*.qmd"

website:
  title: "Development Economics" # Title of website shown on top left
  page-navigation: true
  reader-mode: true
  open-graph: true
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: "üè† Home"
      - href: content/index.qmd
        text: "üè¢ Getting Started"
      - section: "üóìÔ∏è Material"
        contents:
         - href: content/material/index.qmd
           text: Overview
         - href: content/material/SeminarDescription.qmd
           text: Seminar Description
         - href: content/material/session_01.qmd
           text: Session 01
         - href: content/material/session_02.qmd
           text: Session 02
         - href: content/material/session_03.qmd
           text: Session 03
         - href: content/tutorials.qmd
           text: "üíª Tutorials"

  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2025, Claudius Gr√§bner-Radkowitsch" 

bibliography: references/references.bib
csl: references/jepp.csl

format:
  html:
    author-meta: Claudius Gr√§bner-Radkowitsch
    author:
      name: Claudius Gr√§bner-Radkowitsch
      url: https://claudius-graebner.com/
      orcid: 0000-0003-4065-4722
      affiliation: EUF and JKU
      affiliation-url: https://www.uni-flensburg.de/en/pluralist-economics
    date-format: "DD MM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: false

    theme:
      light: 
        - journal
        - css/custom.scss # Change the default colour
    toc: true

execute:
  freeze: auto

